/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: dictionary.h 6372 2014-01-17 09:58:50Z kainz $
 */

/**
 * \file
 *         Topic dictionary extension.
 *         Project specific topic identifiers and attribute keys are defined here.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef DETECTOR_DICTIONARY_TOPIC_H
#define DETECTOR_DICTIONARY_TOPIC_H

/******************************************************************************/
/***   Defines                                                              ***/
/******************************************************************************/
// Defines for topic identifiers (use as value for xme_core_topic_t):

#define DETECTOR_TOPIC_DEVICE_INFO 4098 ///< Identifier for topic 'device_info' (data type: device_info).

#endif // #ifndef DETECTOR_DICTIONARY_TOPIC_H
