/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: dictionary.h 6351 2014-01-15 16:03:40Z geisinger $
 */

/**
 * \file
 *         Topic dictionary extension.
 *         Project specific topic identifiers and attribute keys are defined here.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef CONFIGURATOREXTENSION_DICTIONARY_TOPIC_H
#define CONFIGURATOREXTENSION_DICTIONARY_TOPIC_H

/******************************************************************************/
/***   Defines                                                              ***/
/******************************************************************************/
// Defines for topic identifiers (use as value for xme_core_topic_t):

#define CONFIGURATOREXTENSION_TOPIC_DATA 4098 ///< Identifier for topic 'data' (data type: data).

// Defines for attribute keys (use as value for xme_core_attribute_key_t):

#define CONFIGURATOREXTENSION_ATTRIBUTE_QUALITY 4098 ///< Key for attribute 'quality' (data type: configuratorExtension_attribute_quality_t).

#endif // #ifndef CONFIGURATOREXTENSION_DICTIONARY_TOPIC_H
