/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: rOSComponent.cpp 6352 2014-01-15 16:12:08Z kainz $
 */

/**
 * \file
 *         Source file for ROS component.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "rOSGateway/adv/rOS/include/rOSComponent.h"

// PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_INCLUDES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Defines                                                              ***/
/******************************************************************************/

// PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_DEFINES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/

// PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_TYPE_DEFINITIONS) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Variables                                                            ***/
/******************************************************************************/

// PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_VARIABLES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/

// PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_PROTOTYPES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
rOSGateway_adv_rOS_rOSComponent_init
(
    rOSGateway_adv_rOS_rOSComponent_config_t* const config,
    const char* initializationString
)
{
    // PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_INITIALIZE) ENABLED START
    XME_UNUSED_PARAMETER(config);
    XME_UNUSED_PARAMETER(initializationString);
    
    return XME_STATUS_SUCCESS;
    // PROTECTED REGION END
}

void
rOSGateway_adv_rOS_rOSComponent_fini
(
    rOSGateway_adv_rOS_rOSComponent_config_t* const config
)
{
    // PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_FINALIZE) ENABLED START
    XME_UNUSED_PARAMETER(config);
    // PROTECTED REGION END
}

// PROTECTED REGION ID(ROSGATEWAY_ADV_ROS_ROSCOMPONENT_C_IMPLEMENTATION) ENABLED START
// PROTECTED REGION END
