/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: senderComponent.c 6391 2014-01-20 13:02:32Z wiesmueller $
 */

/**
 * \file
 *         Source file for sender component.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "queues/adv/sender/include/senderComponent.h"

// PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_INCLUDES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Defines                                                              ***/
/******************************************************************************/

// PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_DEFINES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/

// PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_TYPE_DEFINITIONS) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Variables                                                            ***/
/******************************************************************************/

// PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_VARIABLES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/

// PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_PROTOTYPES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
queues_adv_sender_senderComponent_init
(
    queues_adv_sender_senderComponent_config_t* const config,
    const char* initializationString
)
{
    // PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_INITIALIZE) ENABLED START
    static uint8_t instanceCount = 1U;
    
    XME_UNUSED_PARAMETER(initializationString);
    
    config->instanceNumber = instanceCount++;
    
    return XME_STATUS_SUCCESS;
    // PROTECTED REGION END
}

void
queues_adv_sender_senderComponent_fini
(
    queues_adv_sender_senderComponent_config_t* const config
)
{
    // PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_FINALIZE) ENABLED START
    
    // Nothing to do
    
    XME_UNUSED_PARAMETER(config);
    
    // PROTECTED REGION END
}

// PROTECTED REGION ID(QUEUES_ADV_SENDER_SENDERCOMPONENT_C_IMPLEMENTATION) ENABLED START

// PROTECTED REGION END
