/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: loginClientComponentWrapper.h 4893 2013-08-30 16:20:57Z wiesmueller $
 */

/**
 * \file
 *         Component wrapper - implements interface of a component
 *              to the data handler
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_H
#define XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/executionManager/include/executionManagerDataStructures.h"

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_H_INCLUDES) ENABLED START

#include "xme/core/topicData.h"

// PROTECTED REGION END

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/
XME_EXTERN_C_BEGIN

/**
 * \enum   xme_core_login_loginClientComponentWrapper_internalPortId_t
 *
 * \brief  Defines internal port ids of component 'loginClient'.
 *
 * \details These can be used when calling the xme_core_login_loginClientComponentWrapper_receivePort function.
 *
 * \see    xme_core_login_loginClientComponentWrapper_receivePort
 */
typedef enum
{
    XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_PORT_INRESPONSE = 0, ///< Port 'inResponse'
    XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_PORT_OUTREQUEST = 1, ///< Port 'outRequest'
    XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_PORT_OUTLOGINACKNOWLEDGMENT = 2 ///< Port 'outLoginAcknowledgment'
} xme_core_login_loginClientComponentWrapper_internalPortId_t;

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/
/**
 * \brief  Associate an internal port number with the corresponding port handle.
 *         For the ids of the individual ports, see the definition of xme_core_login_loginClientComponentWrapper_internalPortId_t.
 *
 * \param  dataPacketId Port handle from the dataHandler.
 * \param  componentInternalPortId Component internal port number of the above port.
 * 
 * \retval XME_STATUS_SUCCESS if no problems occurred.
 * \retval XME_STATUS_INVALID_PARAMETER if componentInternalPortId is unknown.
 */
xme_status_t
xme_core_login_loginClientComponentWrapper_receivePort
(
    xme_core_dataManager_dataPacketId_t dataPacketId,
    xme_core_login_loginClientComponentWrapper_internalPortId_t componentInternalPortId
);

/**
 * \brief  This function is called by the function wrapper after the step
 *         function has been called. It signals to the middleware that all
 *         input ports have been read.
 */
void
xme_core_login_loginClientComponentWrapper_completeReadOperations(void);

/**
 * \brief  This function is called by the function wrapper after the step
 *         function has been called. It signals to the middleware that all
 *         write operations on ports that actually have been written to 
 *         in the step function (via the functions in this component wrapper)
 *         are now completed.
 */
void
xme_core_login_loginClientComponentWrapper_completeWriteOperations(void);

/**
 * \brief  Read data from port inResponse.
 *
 * \param  data User provided storage, to which the data is copied.
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginClientComponentWrapper_readPortInResponse
(
    xme_core_topic_login_loginResponse_t* data
);

/**
 * \brief  Write data to port outRequest.
 *
 * \param  data User provided storage, from which the data is copied.
 *              When NULL no data will be written to the port (this
 *              is also treated as  success).
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginClientComponentWrapper_writePortOutRequest
(
    xme_core_topic_login_loginRequest_t* data
);

/**
 * \brief  Write data to port outLoginAcknowledgment.
 *
 * \param  data User provided storage, from which the data is copied.
 *              When NULL no data will be written to the port (this
 *              is also treated as  success).
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginClientComponentWrapper_writePortOutLoginAcknowledgment
(
    xme_core_topic_login_loginAcknowledgment_t* data
);


XME_EXTERN_C_END

#endif // #ifndef XME_CORE_LOGIN_LOGINCLIENTCOMPONENTWRAPPER_H
