/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: loginManagerComponentWrapper.h 4893 2013-08-30 16:20:57Z wiesmueller $
 */

/**
 * \file
 *         Component wrapper - implements interface of a component
 *              to the data handler
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H
#define XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/executionManager/include/executionManagerDataStructures.h"

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H_INCLUDES) ENABLED START

#include "xme/core/topicData.h"

// PROTECTED REGION END

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/
XME_EXTERN_C_BEGIN

/**
 * \enum   xme_core_login_loginManagerComponentWrapper_internalPortId_t
 *
 * \brief  Defines internal port ids of component 'loginManager'.
 *
 * \details These can be used when calling the xme_core_login_loginManagerComponentWrapper_receivePort function.
 *
 * \see    xme_core_login_loginManagerComponentWrapper_receivePort
 */
typedef enum
{
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_INLOGINREQUEST = 0, ///< Port 'inLoginRequest'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_INPNPLOGINRESPONSE = 1, ///< Port 'inPnPLoginResponse'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_OUTPNPLOGINREQUEST = 2, ///< Port 'outPnPLoginRequest'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_OUTLOGINRESPONSE = 3 ///< Port 'outLoginResponse'
} xme_core_login_loginManagerComponentWrapper_internalPortId_t;

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/
/**
 * \brief  Associate an internal port number with the corresponding port handle.
 *         For the ids of the individual ports, see the definition of xme_core_login_loginManagerComponentWrapper_internalPortId_t.
 *
 * \param  dataPacketId Port handle from the dataHandler.
 * \param  componentInternalPortId Component internal port number of the above port.
 * 
 * \retval XME_STATUS_SUCCESS if no problems occurred.
 * \retval XME_STATUS_INVALID_PARAMETER if componentInternalPortId is unknown.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_receivePort
(
    xme_core_dataManager_dataPacketId_t dataPacketId,
    xme_core_login_loginManagerComponentWrapper_internalPortId_t componentInternalPortId
);

/**
 * \brief  This function is called by the function wrapper after the step
 *         function has been called. It signals to the middleware that all
 *         input ports have been read.
 */
void
xme_core_login_loginManagerComponentWrapper_completeReadOperations(void);

/**
 * \brief  This function is called by the function wrapper after the step
 *         function has been called. It signals to the middleware that all
 *         write operations on ports that actually have been written to 
 *         in the step function (via the functions in this component wrapper)
 *         are now completed.
 */
void
xme_core_login_loginManagerComponentWrapper_completeWriteOperations(void);

/**
 * \brief  Read data from port inLoginRequest.
 *
 * \details Port description:
 *            The subscription is related with login requests received from the LoginClient.
 *
 * \param  data User provided storage, to which the data is copied.
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_readPortInLoginRequest
(
    xme_core_topic_login_loginRequest_t* data
);

/**
 * \brief  Read data from port inPnPLoginResponse.
 *
 * \details Port description:
 *            This subscription corresponds to the response obtained from the pnpManager. 
 *
 * \param  data User provided storage, to which the data is copied.
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_readPortInPnPLoginResponse
(
    xme_core_topic_login_pnpLoginResponse_t* data
);

/**
 * \brief  Write data to port outPnPLoginRequest.
 *
 * \details Port description:
 *          The publication is related to login response after processing the login request. 
 *
 * \param  data User provided storage, from which the data is copied.
 *              When NULL no data will be written to the port (this
 *              is also treated as  success).
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_writePortOutPnPLoginRequest
(
    xme_core_topic_login_pnpLoginRequest_t* data
);

/**
 * \brief  Write data to port outLoginResponse.
 *
 * \details Port description:
 *          This publication corresponds to the login response. 
 *
 * \param  data User provided storage, from which the data is copied.
 *              When NULL no data will be written to the port (this
 *              is also treated as  success).
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_writePortOutLoginResponse
(
    xme_core_topic_login_loginResponse_t* data
);


XME_EXTERN_C_END

#endif // #ifndef XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H
