/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: loginManagerProcessRequestFunction.c 5079 2013-09-17 07:53:06Z ruiz $
 */

/**
 * \file
 *         Source file for function loginManagerProcessRequest in component loginManager.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/login/include-gen/loginManagerProcessRequestFunction.h"

#include "xme/core/login/include-gen/loginManagerProcessRequestFunctionWrapper.h"
#include "xme/core/login/include-gen/loginManagerComponentWrapper.h"

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_C_INCLUDES) ENABLED START
#include "xme/wp/waypointConfigInfrastructure.h"
#include "xme/core/login/include/loginManager.h"
#include <inttypes.h>
// PROTECTED REGION END

/******************************************************************************/
/***   Static variables                                                     ***/
/******************************************************************************/
/**
 * \brief  Variable holding the value of the required output port 'outPnPLoginRequest'.
 *
 * \details If necessary initialize this in the init function.
 *          The value of this variable will be written to the port at the end of
 *          the step function.
 */
static xme_core_topic_login_pnpLoginRequest_t
portOutPnPLoginRequestData;

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_C_STATICVARIABLES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
xme_core_login_loginManagerProcessRequestFunction_init
(
    void* param
)
{
    // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_INITIALIZE_C) ENABLED START
    
    // TODO: Auto-generated stub
    
    XME_UNUSED_PARAMETER(param);
    
    return XME_STATUS_SUCCESS;
    
    // PROTECTED REGION END
}

void
xme_core_login_loginManagerProcessRequestFunction_step
(
    void* param
)
{
    xme_status_t status[1];
    
    xme_core_topic_login_loginRequest_t portInLoginRequestData; // Required port.
    xme_core_topic_login_pnpLoginRequest_t* portOutPnPLoginRequestDataPtr = &portOutPnPLoginRequestData;
    
    status[0] = xme_core_login_loginManagerComponentWrapper_readPortInLoginRequest(&portInLoginRequestData);
    
    {
        // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_STEP_C) ENABLED START
        xme_com_interface_address_t interfaceAddress;
        char strIPAddress[XME_COM_INTERFACE_IPV4_STRING_BUFFER_SIZE];

        // TODO: Auto-generated stub
    
        XME_UNUSED_PARAMETER(param);
        XME_CHECK_MSG
        (
            XME_STATUS_SUCCESS == status[0], 
            XME_CHECK_RVAL_VOID, 
            XME_LOG_WARNING, 
            "The input parameter cannot be get.\n"
        );

        XME_CHECK_MSG
        (
            XME_STATUS_SUCCESS == xme_com_interface_ipv4ToGenericAddress
            (
                portInLoginRequestData.ipAddress, 
                portInLoginRequestData.ipAddress >> 8, 
                portInLoginRequestData.ipAddress >> 16, 
                portInLoginRequestData.ipAddress >> 24, 
                xme_hal_net_ntohs(portInLoginRequestData.portAddress),
                &interfaceAddress
            ),
            XME_CHECK_RVAL_VOID,
            XME_LOG_ERROR,
            "Cannot get the interface address from the login request.\n"
        );

        XME_CHECK_MSG
        (
            XME_STATUS_SUCCESS == xme_com_interface_genericAddressToIPv4String
            (
                &interfaceAddress, strIPAddress, XME_COM_INTERFACE_IPV4_STRING_BUFFER_SIZE
            ),
            XME_CHECK_RVAL_VOID,
            XME_LOG_ERROR,
            "Cannot transform ip address to string.\n"
        );

        XME_LOG
        (
            XME_LOG_NOTE, 
            "[LoginManager] Received a Login Request from guid=%" PRIu64 ". The calling IP address is: %s \n", 
            portInLoginRequestData.guid, 
            strIPAddress
        );

        XME_CHECK_MSG
        (
            XME_STATUS_SUCCESS == xme_core_login_loginManager_loginRequest(&portInLoginRequestData, portOutPnPLoginRequestDataPtr),
            XME_CHECK_RVAL_VOID,
            XME_LOG_ERROR,
            "The return value for login request was unsuccess.\n"
        );
        
        XME_CHECK_MSG
        (
            XME_STATUS_SUCCESS == xme_wp_wci_addConfig(portInLoginRequestData.ipAddress, portInLoginRequestData.portAddress, XME_CORE_TOPIC_LOGIN_LOGINRESPONSE),
            XME_CHECK_RVAL_VOID,
            XME_LOG_ERROR,
            "The return value for adding the configuration for login response was unsuccess.\n"
        );

        XME_LOG
        (
            XME_LOG_NOTE, 
            "[LoginManager] Sending a PnP Login Request for node %d. \n", 
            portOutPnPLoginRequestDataPtr->nodeId
        );

        // PROTECTED REGION END
    }
    
    status[0] = xme_core_login_loginManagerComponentWrapper_writePortOutPnPLoginRequest(portOutPnPLoginRequestDataPtr);
    
    {
        // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_STEP_2_C) ENABLED START
    
        XME_CHECK_MSG
        (
            XME_STATUS_SUCCESS == status[0], 
            XME_CHECK_RVAL_VOID, 
            XME_LOG_WARNING, 
            "The write port operation failed."
        );
    
        // PROTECTED REGION END
    }
}

void
xme_core_login_loginManagerProcessRequestFunction_fini(void)
{
    // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_TERMINATE_C) ENABLED START
    
    // TODO: Auto-generated stub
    
    // PROTECTED REGION END
}

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINMANAGERPROCESSREQUESTFUNCTION_IMPLEMENTATION_C) ENABLED START

// PROTECTED REGION END
