/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: loginClientSendRequestFunction.c 5062 2013-09-16 08:47:39Z gulati $
 */

/**
 * \file
 *         Source file for function loginClientSendRequest in component loginClient.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/login/include-gen/loginClientSendRequestFunction.h"

#include "xme/core/login/include-gen/loginClientSendRequestFunctionWrapper.h"
#include "xme/core/login/include-gen/loginClientComponentWrapper.h"

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_C_INCLUDES) ENABLED START
#include "xme/core/login/include/loginClient.h"
// PROTECTED REGION END

/******************************************************************************/
/***   Static variables                                                     ***/
/******************************************************************************/
/**
 * \brief  Variable holding the value of the required output port 'outRequest'.
 *
 * \details If necessary initialize this in the init function.
 *          The value of this variable will be written to the port at the end of
 *          the step function.
 */
static xme_core_topic_login_loginRequest_t
portOutRequestData;

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_C_STATICVARIABLES) ENABLED START
/**
 * \brief Variable to keep the count for interval to broadcast the login request.
 */
int count=0;
// PROTECTED REGION END

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
xme_core_login_loginClientSendRequestFunction_init
(
    void* param
)
{
    // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_INITIALIZE_C) ENABLED START
    xme_status_t initStatus;
    xme_status_t fillLoginRequestStatus;

    XME_UNUSED_PARAMETER(param);

    initStatus = xme_core_login_loginClient_init();

    if (XME_STATUS_SUCCESS != initStatus)
    {
        XME_LOG
        (
            XME_LOG_NOTE, 
            "[LoginClient] Cannot init the login client. Return status: %d \n", 
            initStatus
        );
    }

    fillLoginRequestStatus = xme_core_login_loginClient_fillLoginRequest(&portOutRequestData);
    
    if (XME_STATUS_SUCCESS != fillLoginRequestStatus)
    {
        XME_LOG
        (
            XME_LOG_NOTE, 
            "[LoginClient] Cannot fill login request. Return status: %d \n", 
            fillLoginRequestStatus
        );
    }

    return XME_STATUS_SUCCESS;
    
    // PROTECTED REGION END
}

void
xme_core_login_loginClientSendRequestFunction_step
(
    void* param
)
{
    xme_status_t status[1];
    
    xme_core_topic_login_loginRequest_t* portOutRequestDataPtr = &portOutRequestData;
    
    {
        // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_STEP_C) ENABLED START

        XME_UNUSED_PARAMETER(param);
        if (portOutRequestData.nodeId != XME_CORE_NODE_INVALID_NODE_ID || 0 != count)
            portOutRequestDataPtr = NULL;   
        else if (10 == count++)
            count = 0;
        if(portOutRequestDataPtr != NULL)
            XME_LOG(XME_LOG_NOTE, "[loginClientSendRequestFunction] Broadcasting a Login Request\n");

        // PROTECTED REGION END
    }
    
    status[0] = xme_core_login_loginClientComponentWrapper_writePortOutRequest(portOutRequestDataPtr);
    
    {
        // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_STEP_2_C) ENABLED START

        if (XME_STATUS_SUCCESS != status[0])
            XME_LOG(XME_LOG_DEBUG, "[loginClientSendRequestFunction] Failed to write the Login Request to port %d\n", status[0]);

        // PROTECTED REGION END
    }
}

void
xme_core_login_loginClientSendRequestFunction_fini(void)
{
    // PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_TERMINATE_C) ENABLED START
    
    // TODO: Auto-generated stub
    
    // PROTECTED REGION END
}

// PROTECTED REGION ID(XME_CORE_LOGIN_LOGINCLIENTSENDREQUESTFUNCTION_IMPLEMENTATION_C) ENABLED START

// PROTECTED REGION END
