/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: detectorComponent.c 6372 2014-01-17 09:58:50Z kainz $
 */

/**
 * \file
 *         Source file for detector component.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "detector/adv/detector/include/detectorComponent.h"

// PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_INCLUDES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Defines                                                              ***/
/******************************************************************************/

// PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_DEFINES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/

// PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_TYPE_DEFINITIONS) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Variables                                                            ***/
/******************************************************************************/

// PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_VARIABLES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/

// PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_PROTOTYPES) ENABLED START
// PROTECTED REGION END

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
detector_adv_detector_detectorComponent_init
(
    detector_adv_detector_detectorComponent_config_t* const config,
    const char* initializationString
)
{
    // PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_INITIALIZE) ENABLED START
    XME_UNUSED_PARAMETER(initializationString);

	config->state = CREATE_DEVICE_CAMERA;

    return XME_STATUS_SUCCESS;
    // PROTECTED REGION END
}

void
detector_adv_detector_detectorComponent_fini
(
    detector_adv_detector_detectorComponent_config_t* const config
)
{
    // PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_FINALIZE) ENABLED START
    XME_UNUSED_PARAMETER(config);
    // PROTECTED REGION END
}

// PROTECTED REGION ID(DETECTOR_ADV_DETECTOR_DETECTORCOMPONENT_C_IMPLEMENTATION) ENABLED START
// PROTECTED REGION END
