/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: subscriberComponent.c 7685 2014-03-05 15:21:06Z geisinger $
 */

/**
 * \file
 *         Source file for subscriber component.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "configuratorExtension/adv/subscriber/include/subscriberComponent.h"

// PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_INCLUDES) ENABLED START

#include "xme/core/log.h"

// PROTECTED REGION END

/******************************************************************************/
/***   Defines                                                              ***/
/******************************************************************************/

// PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_DEFINES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/

// PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_TYPE_DEFINITIONS) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Variables                                                            ***/
/******************************************************************************/

// PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_VARIABLES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/

// PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_PROTOTYPES) ENABLED START

// PROTECTED REGION END

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
configuratorExtension_adv_subscriber_subscriberComponent_init
(
    configuratorExtension_adv_subscriber_subscriberComponent_config_t* const config,
    const char* initializationString
)
{
    // PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_INITIALIZE) ENABLED START

    XME_UNUSED_PARAMETER(config);

    XME_LOG(XME_LOG_ALWAYS, "Creating subscriber with initialization string '%s'\n", initializationString);

    return XME_STATUS_SUCCESS;

    // PROTECTED REGION END
}

void
configuratorExtension_adv_subscriber_subscriberComponent_fini
(
    configuratorExtension_adv_subscriber_subscriberComponent_config_t* const config
)
{
    // PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_FINALIZE) ENABLED START

    XME_UNUSED_PARAMETER(config);

    XME_LOG(XME_LOG_ALWAYS, "Removing subscriber\n");

    // PROTECTED REGION END
}

// PROTECTED REGION ID(CONFIGURATOREXTENSION_ADV_SUBSCRIBER_SUBSCRIBERCOMPONENT_C_IMPLEMENTATION) ENABLED START

// PROTECTED REGION END
