/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Topic utility functions.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "topicUtil.h"
#include "chromosomeGui/topic/dictionary.h"
#include "chromosomeGui/topic/dictionaryData.h"

#include "xme/core/topicData.h"

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
uint16_t
xme_core_topicUtil_getTopicSize
(
    xme_core_topic_t topic
)
{
    uint16_t size;
    
    switch ((uint64_t) topic)
    {
        case CHROMOSOMEGUI_TOPIC_BUTTONSIGNAL:
            size = (uint16_t) sizeof(chromosomeGui_topic_ButtonSignal_t);
            break;
        case CHROMOSOMEGUI_TOPIC_WRITETEXT:
            size = (uint16_t) sizeof(chromosomeGui_topic_WriteText_t);
            break;
        case XME_CORE_TOPIC_PNPMANAGER_RUNTIME_GRAPH_MODEL:
            size = (uint16_t) sizeof(xme_core_topic_pnpManager_runtime_graph_model_t);
            break;
        case XME_CORE_TOPIC_LOGIN_LOGINREQUEST:
            size = (uint16_t) sizeof(xme_core_topic_login_loginRequest_t);
            break;
        case XME_CORE_TOPIC_LOGIN_LOGINRESPONSE:
            size = (uint16_t) sizeof(xme_core_topic_login_loginResponse_t);
            break;
        case XME_CORE_TOPIC_LOGIN_PNPLOGINREQUEST:
            size = (uint16_t) sizeof(xme_core_topic_login_pnpLoginRequest_t);
            break;
        case XME_CORE_TOPIC_LOGIN_PNPLOGINRESPONSE:
            size = (uint16_t) sizeof(xme_core_topic_login_pnpLoginResponse_t);
            break;
        case XME_CORE_TOPIC_LOGIN_LOGINACKNOWLEDGMENT:
            size = (uint16_t) sizeof(xme_core_topic_login_loginAcknowledgment_t);
            break;
        case XME_CORE_TOPIC_PNP_COMPONENTINSTANCEMANIFEST:
            size = (uint16_t) sizeof(xme_core_topic_pnp_componentInstanceManifest_t);
            break;
        default:
            size = 0;
    }
    
    return size;
}
