set(_CATKIN_CURRENT_PACKAGE "ros_system")
set(ros_system_MAINTAINER "Gerd Kainz <kainz@fortiss.org>")
set(ros_system_DEPRECATED "")
set(ros_system_VERSION "0.0.0")
set(ros_system_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation")
set(ros_system_RUN_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(ros_system_BUILDTOOL_DEPENDS "catkin")