/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: calculatorManifest.c 7769 2014-03-11 15:27:13Z geisinger $
 */

/**
 * \file
 *         Defines function for creation of component type manifest
 *         for 'calculator'.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "calculator/adv/calculator/include/calculatorManifest.h"

#include "../include/calculatorComponentWrapper.h"
#include "calculator/adv/calculator/include/calculateFunction.h"
#include "calculator/adv/calculator/include/calculateFunctionWrapper.h"
#include "calculator/adv/calculator/include/calculatorComponent.h"
#include "calculator/topic/dictionary.h"
#include "xme/core/log.h"
#include "xme/hal/include/time.h"

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
calculator_adv_calculator_manifest_createComponentTypeManifest
(
    xme_core_componentManifest_t* componentManifest
)
{
    XME_CHECK
    (
        NULL != componentManifest,
        XME_STATUS_INVALID_PARAMETER
    );

    (void)xme_hal_mem_set(componentManifest, 0U, sizeof(xme_core_componentManifest_t));

    componentManifest->componentType = (xme_core_componentType_t)5000;
    componentManifest->componentWrapperInit = calculator_adv_calculator_calculatorComponentWrapper_init;
    componentManifest->componentWrapperReceivePort = calculator_adv_calculator_calculatorComponentWrapper_receivePort;
    componentManifest->componentWrapperFini = calculator_adv_calculator_calculatorComponentWrapper_fini;
    componentManifest->componentInit = (xme_core_componentManifest_componentInit_t)calculator_adv_calculator_calculatorComponent_init;
    (void)xme_hal_safeString_strncpy(componentManifest->name, "calculator", sizeof(componentManifest->name));
    componentManifest->configStructSize = sizeof(calculator_adv_calculator_calculatorComponent_config_t);

    {
        uint32_t functionArrayLength = sizeof(componentManifest->functionManifests) / sizeof(componentManifest->functionManifests[0]);

        // Function 'calculate'
        {
            if (0U >= functionArrayLength) // Check generated by tool (which does not know about the array size)
            {
                if (0U == functionArrayLength) // Only trigger warning once
                {
                    XME_LOG
                    (
                        XME_LOG_WARNING,
                        "%s:%d Component type 'calculator' defines more functions (%d) than can be stored in the manifest data structure (%d).\n",
                        __FILE__,
                        __LINE__,
                       1,
                       functionArrayLength
                    );
                }
            }
            else
            {
                xme_core_functionManifest_t* functionManifest;
                
                functionManifest = &componentManifest->functionManifests[0];
                functionManifest->functionId = (xme_core_component_functionId_t)1;
                functionManifest->wcet = xme_hal_time_timeIntervalFromMilliseconds(20ull);
                functionManifest->alphaCurve.alphaCurve = 0;
                functionManifest->completion = true;
                functionManifest->requiredPortIndicesLength = 2;
                functionManifest->requiredPortIndices[0] = (calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t)CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_PORT_CALCULATORREQUEST;
                functionManifest->requiredPortIndices[1] = (calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t)CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_PORT_CALCULATORRESPONSE;
                functionManifest->optionalPortIndicesLength = 0;
                functionManifest->functionInit = (xme_core_exec_initCallback_t)calculator_adv_calculator_calculateFunction_init;
                functionManifest->functionFini = (xme_core_exec_finiCallback_t)calculator_adv_calculator_calculateFunction_fini;
                functionManifest->functionWrapperExecute = calculator_adv_calculator_calculateFunctionWrapper_execute;
            }
        }
    }

    {
        uint32_t portArrayLength;
        portArrayLength = sizeof(componentManifest->portManifests) / sizeof(componentManifest->portManifests[0]);

        // Subscription 'calculatorRequest'
        {
            if (0 >= portArrayLength) // Check generated by tool (which does not know about the array size)
            {
                if (0 == portArrayLength) // Only trigger warning once
                {
                    XME_LOG
                    (
                        XME_LOG_WARNING,
                        "%s:%d Component type 'calculator' defines more ports (%d) than can be stored in the manifest data structure (%d).\n",
                        __FILE__,
                        __LINE__,
                        2,
                        portArrayLength
                    );
                }
            }
            else
            {
                xme_core_componentPortManifest_t* portManifest;
            
                portManifest = &componentManifest->portManifests[0];
                portManifest->portType = XME_CORE_COMPONENT_PORTTYPE_RR_REQUEST_HANDLER;
                portManifest->topic = CALCULATOR_TOPIC_CALCULATORREQUEST; 
                portManifest->lowerConnectionBound = 0u;
                portManifest->upperConnectionBound = XME_CORE_COMPONENT_CONNECTIONBOUND_UNBOUNDED;
                portManifest->queueSize = 1;
                portManifest->persistent = false;
        
                portManifest->attrSet = XME_CORE_ATTRIBUTE_EMPTY_ATTRIBUTE_SET;
            }
        }
        // Publication 'calculatorResponse'
        {
            if (1 >= portArrayLength) // Check generated by tool (which does not know about the array size)
            {
                if (1 == portArrayLength) // Only trigger warning once
                {
                    XME_LOG
                    (
                        XME_LOG_WARNING,
                        "%s:%d Component type 'calculator' defines more ports (%d) than can be stored in the manifest data structure (%d).\n",
                        __FILE__,
                        __LINE__,
                        2,
                        portArrayLength
                    );
                }
            }
            else
            {
                xme_core_componentPortManifest_t* portManifest;
            
                portManifest = &componentManifest->portManifests[1];
                portManifest->portType = XME_CORE_COMPONENT_PORTTYPE_RR_RESPONSE_SENDER;
                portManifest->topic = CALCULATOR_TOPIC_CALCULATORRESPONSE; 
                portManifest->lowerConnectionBound = XME_CORE_COMPONENT_CONNECTIONBOUND_INVALID;
                portManifest->upperConnectionBound = XME_CORE_COMPONENT_CONNECTIONBOUND_INVALID;
                portManifest->queueSize = 1;
                portManifest->persistent = false;
        
                portManifest->attrSet = XME_CORE_ATTRIBUTE_EMPTY_ATTRIBUTE_SET;
                
            }
        }
    }
    return XME_STATUS_SUCCESS;
}
