/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/josh/xme/examples/ROSGateway/src/application/ros_system/srv/SubstractTwoInts.srv
 *
 */


#ifndef ROS_SYSTEM_MESSAGE_SUBSTRACTTWOINTS_H
#define ROS_SYSTEM_MESSAGE_SUBSTRACTTWOINTS_H

#include <ros/service_traits.h>


#include <ros_system/SubstractTwoIntsRequest.h>
#include <ros_system/SubstractTwoIntsResponse.h>


namespace ros_system
{

struct SubstractTwoInts
{

typedef SubstractTwoIntsRequest Request;
typedef SubstractTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubstractTwoInts
} // namespace ros_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_system::SubstractTwoInts > {
  static const char* value()
  {
    return "6261ad0e9a1d7803132e49e14b2897b6";
  }

  static const char* value(const ::ros_system::SubstractTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_system::SubstractTwoInts > {
  static const char* value()
  {
    return "ros_system/SubstractTwoInts";
  }

  static const char* value(const ::ros_system::SubstractTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_system::SubstractTwoIntsRequest> should match 
// service_traits::MD5Sum< ::ros_system::SubstractTwoInts > 
template<>
struct MD5Sum< ::ros_system::SubstractTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_system::SubstractTwoInts >::value();
  }
  static const char* value(const ::ros_system::SubstractTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_system::SubstractTwoIntsRequest> should match 
// service_traits::DataType< ::ros_system::SubstractTwoInts > 
template<>
struct DataType< ::ros_system::SubstractTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_system::SubstractTwoInts >::value();
  }
  static const char* value(const ::ros_system::SubstractTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_system::SubstractTwoIntsResponse> should match 
// service_traits::MD5Sum< ::ros_system::SubstractTwoInts > 
template<>
struct MD5Sum< ::ros_system::SubstractTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_system::SubstractTwoInts >::value();
  }
  static const char* value(const ::ros_system::SubstractTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_system::SubstractTwoIntsResponse> should match 
// service_traits::DataType< ::ros_system::SubstractTwoInts > 
template<>
struct DataType< ::ros_system::SubstractTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_system::SubstractTwoInts >::value();
  }
  static const char* value(const ::ros_system::SubstractTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SYSTEM_MESSAGE_SUBSTRACTTWOINTS_H
