/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: calculatorComponentWrapper.h 7769 2014-03-11 15:27:13Z geisinger $
 */

/**
 * \file
 *         Component wrapper - implements interface of a component
 *              to the data handler
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_H
#define CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/executionManager/include/executionManagerDataStructures.h"

#include "calculator/topic/dictionaryData.h"

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/

/**
 * \enum calculator_adv_calculator_calculatorComponentWrapper_internalFunctionId_e
 *
 * \brief Values for identifying functions of calculator component.
 */
enum calculator_adv_calculator_calculatorComponentWrapper_internalFunctionId_e
{
    CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_FUNCTION_CALCULATE = 0  ///< Function 'calculate'
};

/**
 * \enum calculator_adv_calculator_calculatorComponentWrapper_internalPortId_e
 *
 * \brief Values for calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t.
 */
enum calculator_adv_calculator_calculatorComponentWrapper_internalPortId_e
{
    CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_PORT_CALCULATORREQUEST = 0, ///< Port 'calculatorRequest'
    CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_PORT_CALCULATORRESPONSE = 1  ///< Port 'calculatorResponse'
};

/**
 * \typedef calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t
 *
 * \brief Defines internal port ids of component 'calculator'.
 *
 * \details These can be used when calling the calculator_adv_calculator_calculatorComponentWrapper_receivePort function.
 *          For the definition of possible values, see enum calculator_adv_calculator_calculatorComponentWrapper_internalPortId_e.
 */
typedef uint8_t calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t;

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/
XME_EXTERN_C_BEGIN

/**
 * \brief Initializes this component wrapper.
 *
 * \retval XME_STATUS_SUCCESS on success.
 */
xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_init(void);

/**
 * \brief Finalizes this component wrapper.
 */
void
calculator_adv_calculator_calculatorComponentWrapper_fini(void);

/**
 * \brief Associate an internal port number with the corresponding port handle.
 *        For the ids of the individual ports, see the definition of calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t.
 *
 * \param dataPacketId Port handle from the dataHandler.
 * \param componentInternalPortId Component internal port number of the above port.
 *
 * \retval XME_STATUS_SUCCESS if no problems occurred.
 * \retval XME_STATUS_INVALID_PARAMETER if componentInternalPortId is unknown.
 */
xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_receivePort
(
    xme_core_dataManager_dataPacketId_t dataPacketId,
    calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t componentInternalPortId
);

/**
 * \brief This function is called by the function wrapper after the step
 *        function has been called. It signals to the middleware that all
 *        input ports have been read.
 */
void
calculator_adv_calculator_calculatorComponentWrapper_completeReadOperations(void);

/**
 * \brief This function is called by the function wrapper after the step
 *        function has been called. It signals to the middleware that all
 *        write operations on ports that actually have been written to
 *        in the step function (via the functions in this component wrapper)
 *        are now completed.
 */
void
calculator_adv_calculator_calculatorComponentWrapper_completeWriteOperations(void);

/**
 * \brief Read data from request handler port 'calculatorRequest'.
 *
 * \param[out] data User provided storage, to which the data is copied.
 * \param[out] requestDataHandle Handle for the request. Must be passed
 *             to the corresponding calculator_adv_calculator_calculatorComponentWrapper_writeResponseSenderPortCalculatorRequest
 *             call. This is necessary to correlate request and response message.
 *             Do not modify this value manually.
 *
 * \retval XME_STATUS_SUCCESS if reading was successful.
 * \retval XME_STATUS_NO_SUCH_VALUE when there is now new data on this port
 *         (only possible when this port is an optional port of the current function).
 * \retval XME_STATUS_INVALID_PARAMETER if data is NULL, or requestDataHandle is NULL.
 * \retval XME_STATUS_INTERNAL_ERROR in case of any other error.
 */
xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_readRequestHandlerPortCalculatorRequest
(
    const calculator_topic_calculatorRequest_t* data,
    const xme_core_component_requestDataHandle_t* requestDataHandle
);

/**
 * \brief Write data to response sender port 'calculatorResponse'.
 *
 * \param[in] data User provided storage, from which the data is copied.
 *            When NULL no data will be written to the port (this
 *            is also treated as  success).
 * \param[in] Request handle from corresponding call to calculator_adv_calculator_calculatorComponentWrapper_readRequestHandlerPortCalculatorResponse.
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 * \retval XME_STATUS_INVALID_PARAMETER if requestDataHandle is NULL.
 */
xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_writeResponseSenderPortCalculatorResponse
(
    const calculator_topic_calculatorResponse_t* const data,
    const xme_core_component_requestDataHandle_t* const requestDataHandle
);

xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_readInputPortAttribute
(
    calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t portId,
    xme_core_attribute_key_t attributeKey,
    void* const buffer,
    uint32_t bufferSize
);

xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_writeOutputPortAttribute
(
    calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t portId,
    xme_core_attribute_key_t attributeKey,
    const void* const buffer,
    uint32_t bufferSize
);

xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_readNextPacket
(
    calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t portId
);

xme_status_t
calculator_adv_calculator_calculatorComponentWrapper_writeNextPacket
(
    calculator_adv_calculator_calculatorComponentWrapper_internalPortId_t portId
);


XME_EXTERN_C_END

#endif // #ifndef CALCULATOR_ADV_CALCULATOR_CALCULATORCOMPONENTWRAPPER_H
