/*
 * Copyright (c) 2011-2014, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: loginManagerComponentWrapper.h 7837 2014-03-14 12:33:13Z wiesmueller $
 */

/**
 * \file
 *         Component wrapper - implements interface of a component
 *              to the data handler
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H
#define XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/executionManager/include/executionManagerDataStructures.h"

#include "xme/core/topicData.h"

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/

/**
 * \enum xme_core_login_loginManagerComponentWrapper_internalFunctionId_e
 *
 * \brief Values for identifying functions of loginManager component.
 */
enum xme_core_login_loginManagerComponentWrapper_internalFunctionId_e
{
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_FUNCTION_LOGINMANAGERPROCESSREQUEST = 0, ///< Function 'loginManagerProcessRequest'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_FUNCTION_LOGINMANAGERPROCESSRESPONSE = 1, ///< Function 'loginManagerProcessResponse'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_FUNCTION_LOGINMANAGERPROCESSLOGOUTNOTIFICATION = 2  ///< Function 'loginManagerProcessLogoutNotification'
};

/**
 * \enum xme_core_login_loginManagerComponentWrapper_internalPortId_e
 *
 * \brief Values for xme_core_login_loginManagerComponentWrapper_internalPortId_t.
 */
enum xme_core_login_loginManagerComponentWrapper_internalPortId_e
{
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_INLOGINREQUEST = 0, ///< Port 'inLoginRequest'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_INPNPLOGINRESPONSE = 1, ///< Port 'inPnPLoginResponse'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_INLOGOUTNOTIFICATION = 2, ///< Port 'inLogoutNotification'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_OUTPNPLOGINREQUEST = 3, ///< Port 'outPnPLoginRequest'
    XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_PORT_OUTLOGINRESPONSE = 4  ///< Port 'outLoginResponse'
};

/**
 * \typedef xme_core_login_loginManagerComponentWrapper_internalPortId_t
 *
 * \brief Defines internal port ids of component 'loginManager'.
 *
 * \details These can be used when calling the xme_core_login_loginManagerComponentWrapper_receivePort function.
 *          For the definition of possible values, see enum xme_core_login_loginManagerComponentWrapper_internalPortId_e.
 */
typedef uint8_t xme_core_login_loginManagerComponentWrapper_internalPortId_t;

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/
XME_EXTERN_C_BEGIN

/**
 * \brief Initializes this component wrapper.
 *
 * \retval XME_STATUS_SUCCESS on success.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_init(void);

/**
 * \brief Finalizes this component wrapper.
 */
void
xme_core_login_loginManagerComponentWrapper_fini(void);

/**
 * \brief Associate an internal port number with the corresponding port handle.
 *        For the ids of the individual ports, see the definition of xme_core_login_loginManagerComponentWrapper_internalPortId_t.
 *
 * \param dataPacketId Port handle from the dataHandler.
 * \param componentInternalPortId Component internal port number of the above port.
 *
 * \retval XME_STATUS_SUCCESS if no problems occurred.
 * \retval XME_STATUS_INVALID_PARAMETER if componentInternalPortId is unknown.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_receivePort
(
    xme_core_dataManager_dataPacketId_t dataPacketId,
    xme_core_login_loginManagerComponentWrapper_internalPortId_t componentInternalPortId
);

/**
 * \brief This function is called by the function wrapper after the step
 *        function has been called. It signals to the middleware that all
 *        input ports have been read.
 */
void
xme_core_login_loginManagerComponentWrapper_completeReadOperations(void);

/**
 * \brief This function is called by the function wrapper after the step
 *        function has been called. It signals to the middleware that all
 *        write operations on ports that actually have been written to
 *        in the step function (via the functions in this component wrapper)
 *        are now completed.
 */
void
xme_core_login_loginManagerComponentWrapper_completeWriteOperations(void);

/**
 * \brief Read data from port 'inLoginRequest'.
 *
 * \details Port description:
 *            The subscription is related with login requests received from the LoginClient.
 *
 * \param[out] data User provided storage, to which the data is copied.
 *
 * \retval XME_STATUS_SUCCESS if reading was successful.
 * \retval XME_STATUS_NO_SUCH_VALUE when there is now new data on this port
 *         (only possible when this port is an optional port of the current function).
 * \retval XME_STATUS_INVALID_PARAMETER if data is NULL.
 * \retval XME_STATUS_INTERNAL_ERROR in case of any other error.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_readPortInLoginRequest
(
    const xme_core_topic_login_loginRequest_t* data
);

/**
 * \brief Read data from port 'inPnPLoginResponse'.
 *
 * \details Port description:
 *            This subscription corresponds to the response obtained from the pnpManager. 
 *
 * \param[out] data User provided storage, to which the data is copied.
 *
 * \retval XME_STATUS_SUCCESS if reading was successful.
 * \retval XME_STATUS_NO_SUCH_VALUE when there is now new data on this port
 *         (only possible when this port is an optional port of the current function).
 * \retval XME_STATUS_INVALID_PARAMETER if data is NULL.
 * \retval XME_STATUS_INTERNAL_ERROR in case of any other error.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_readPortInPnPLoginResponse
(
    const xme_core_topic_login_pnpLoginResponse_t* data
);

/**
 * \brief Read data from port 'inLogoutNotification'.
 *
 * \details Port description:
 *            Listens to logout notifications from the pnpManager.
 *
 * \param[out] data User provided storage, to which the data is copied.
 *
 * \retval XME_STATUS_SUCCESS if reading was successful.
 * \retval XME_STATUS_NO_SUCH_VALUE when there is now new data on this port
 *         (only possible when this port is an optional port of the current function).
 * \retval XME_STATUS_INVALID_PARAMETER if data is NULL.
 * \retval XME_STATUS_INTERNAL_ERROR in case of any other error.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_readPortInLogoutNotification
(
    const xme_core_topic_pnp_logoutNotification_t* data
);

/**
 * \brief Write data to port 'outPnPLoginRequest'.
 *
 * \details Port description:
 *          The publication is related to login response after processing the login request. 
 *
 * \note The write operation is only allowed to be called once per
 *       data packet sending process. A data packet is sent 
 *       as soon as the xme_core_login_loginManagerComponentWrapper_writeNextPacket()
 *       function is being called or when the step function
 *       returns and data have been written.
 * 
 * \param[in] data User provided storage, from which the data is copied.
 *            When NULL no data will be written to the port (this
 *            is also treated as  success).
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_writePortOutPnPLoginRequest
(
    const xme_core_topic_login_pnpLoginRequest_t* const data
);

/**
 * \brief Write data to port 'outLoginResponse'.
 *
 * \details Port description:
 *          This publication corresponds to the login response. 
 *
 * \note The write operation is only allowed to be called once per
 *       data packet sending process. A data packet is sent 
 *       as soon as the xme_core_login_loginManagerComponentWrapper_writeNextPacket()
 *       function is being called or when the step function
 *       returns and data have been written.
 * 
 * \param[in] data User provided storage, from which the data is copied.
 *            When NULL no data will be written to the port (this
 *            is also treated as  success).
 *
 * \retval XME_STATUS_SUCCESS if operation was successful.
 */
xme_status_t
xme_core_login_loginManagerComponentWrapper_writePortOutLoginResponse
(
    const xme_core_topic_login_loginResponse_t* const data
);

xme_status_t
xme_core_login_loginManagerComponentWrapper_readInputPortAttribute
(
    xme_core_login_loginManagerComponentWrapper_internalPortId_t portId,
    xme_core_attribute_key_t attributeKey,
    void* const buffer,
    uint32_t bufferSize
);

xme_status_t
xme_core_login_loginManagerComponentWrapper_writeOutputPortAttribute
(
    xme_core_login_loginManagerComponentWrapper_internalPortId_t portId,
    xme_core_attribute_key_t attributeKey,
    const void* const buffer,
    uint32_t bufferSize
);

xme_status_t
xme_core_login_loginManagerComponentWrapper_readNextPacket
(
    xme_core_login_loginManagerComponentWrapper_internalPortId_t portId
);

xme_status_t
xme_core_login_loginManagerComponentWrapper_writeNextPacket
(
    xme_core_login_loginManagerComponentWrapper_internalPortId_t portId
);


XME_EXTERN_C_END

#endif // #ifndef XME_CORE_LOGIN_LOGINMANAGERCOMPONENTWRAPPER_H
