# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

#if [ "$color_prompt" = yes ]; then
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#else
#    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
#fi
#unset color_prompt force_color_prompt

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;32m\]$(__git_ps1 "(%s)")\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w$(__git_ps1 " (%s)")\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias cobconsole='rosrun cob_script_server cob_console'

alias bringup='roslaunch cob_bringup robot.launch'
alias dashboard='roslaunch cob_bringup dashboard.launch'
alias navi='roslaunch autopnp_scenario navigation.launch'
alias autopnp='roslaunch autopnp_scenario autopnp_scenario.launch'
alias cdautopnp='roscd autopnp_scenario/scripts'
alias hmiscenario='rosrun autopnp_scenario autopnp_hmi_scenario.py'

alias vacuum_init='rosservice call /vacuum_cleaner_controller/init'
alias vacuum_recover='rosservice call /vacuum_cleaner_controller/recover'
alias vacuum_on='rosservice call /vacuum_cleaner_controller/power_on'
alias vacuum_off='rosservice call /vacuum_cleaner_controller/power_off'

#alias toolchanger_close='rosservice call /cob_phidgets_toolchanger/ifk_toolchanger/set_digital "{uri: 'tool_changer_pin2', state: 1}"'
#alias toolchanger_close_reset='rosservice call /cob_phidgets_toolchanger/ifk_toolchanger/set_digital "{uri: 'tool_changer_pin2', state: 0}"'
#alias toolchanger_open='rosservice call /cob_phidgets_toolchanger/ifk_toolchanger/set_digital "{uri: 'tool_changer_pin4', state: 1}"'
#alias toolchanger_open_reset='rosservice call /cob_phidgets_toolchanger/ifk_toolchanger/set_digital "{uri: 'tool_changer_pin4', state: 0}"'
alias toolchanger_open='~/git/autopnp/autopnp_scenario/scripts/toolchanger_open.sh'
alias toolchanger_close='~/git/autopnp/autopnp_scenario/scripts/toolchanger_close.sh'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# use global color settings
source /etc/cob.bash.bashrc

# provide setup scripts for all users
export PATH=/u/robot/git/setup:$PATH

#source /opt/ros/groovy/setup.bash
source /u/robot/git/care-o-bot_catkin/devel/setup.bash
#source /u/rmb/git/care-o-bot_catkin/devel/setup.bash
export ROS_PACKAGE_PATH=/u/robot/git/care-o-bot:$ROS_PACKAGE_PATH
export ROS_PACKAGE_PATH=~/git/care-o-bot:$ROS_PACKAGE_PATH
export ROS_PACKAGE_PATH=~/git/autopnp:$ROS_PACKAGE_PATH
export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/


export ROS_MASTER_URI=http://cob3-2-pc1:11311
export ROBOT=cob3-2b
export ROBOT_ENV=ipa-apartment
export ROSLAUNCH_SSH_UNKNOWN=1
export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64

COUNT=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
COUNT=$(echo "$COUNT*2" | bc)
export ROS_PARALLEL_JOBS=-j$COUNT
