/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id: funcFunction.h 4948 2013-09-04 08:25:51Z ruiz $
 */

/**
 * \file
 *         Header file for function func in component wrapperTest.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef XME_ADV_WRAPPERTEST_FUNCFUNCTION_H
#define XME_ADV_WRAPPERTEST_FUNCFUNCTION_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/component.h"

XME_EXTERN_C_BEGIN

/******************************************************************************/
/***   Global variables                                                     ***/
/******************************************************************************/
/**
 * \brief  Different mode values will trigger different behaviour of the
 *         step function. Meant to be used by the wrapper tests.
 *
 * \details Mode | Behaviour
 *             0 | Write NULL to optional output port out1.
 *             2 | Write NULL to required port out0.
 */
extern uint8_t xme_adv_wrapperTest_mode;

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/
/**
 * \brief  Initialization of function. 
 *  
 * \details Called once before the function is executed the first time.
 *
 * \param  param Function-specific initialization parameter.
 *
 * \return XME_STATUS_SUCCESS when initialization was successful.
 */
xme_status_t
xme_adv_wrapperTest_funcFunction_init
(
    void* param
);

/**
 * \brief  Executes the function one time.
 *
 * \details Input ports of the function need to be prepared, before calling this.
 *
 * \param  param Function-specific parameter
 */
void
xme_adv_wrapperTest_funcFunction_step
(
    void* param
);

/**
 * \brief  Finalization function.
 *
 * \details Called after function will no longer be executed to free allocated resources.
 *          Function must not be executed after fini has been called.
 */
void
xme_adv_wrapperTest_funcFunction_fini(void);

XME_EXTERN_C_END

#endif // #ifndef XME_ADV_WRAPPERTEST_FUNCFUNCTION_H
