(cl:defpackage ros_system-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SUBSTRACTTWOINTS"
   "<SUBSTRACTTWOINTS-REQUEST>"
   "SUBSTRACTTWOINTS-REQUEST"
   "<SUBSTRACTTWOINTS-RESPONSE>"
   "SUBSTRACTTWOINTS-RESPONSE"
  ))

