set(_CATKIN_CURRENT_PACKAGE "master")
set(master_MAINTAINER "Gerd Kainz <kainz@fortiss.org>")
set(master_DEPRECATED "")
set(master_VERSION "0.0.0")
set(master_BUILD_DEPENDS "roscpp" "std_msgs" "rostime" "ros_system")
set(master_RUN_DEPENDS "roscpp" "std_msgs" "rostime" "ros_system")
set(master_BUILDTOOL_DEPENDS "catkin")